import "%modules%/header/header";
import "%modules%/about/about";
import "%modules%/advantages/advantages";
import "%modules%/use/use";
import "%modules%/products/products";
import "%modules%/serie/serie";
import "%modules%/facade/facade";
import "%modules%/fence/fence";
import "%modules%/wares/wares";
import "%modules%/choice/choice";
import "%modules%/loop/loop";
import "%modules%/works/works";
import "%modules%/contact/contact";
import "%modules%/footer/footer"